### ISSUE TITLE
Fix: button content

### ISSUE THREAD

**Issue by rajat-mehra05** [Kingshuk-Deb/Shortify#1]
The web app looks really good! Congrats for that. 
Suggestions from my side:

1. after successful shortening of link, instead of showing `Try Again` on `button`,
you can simply display other text part like `Success` or `Try new URL`.

2. Or you can display the shortened URL below with in-built copy functionality.

Let me know if these suggestions are helpful. :)

**Comment by Kingshuk-Deb** [comment]
Thanks for those suggestions! I have implemented them accordingly.
